apiVersion: apps/v1
kind: Deployment
metadata:
  name: healthcheck-app
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: healthcheck-app
  template:
    metadata:
      labels:
        app: healthcheck-app
    spec:
      containers:
        - name: healthcheck-container
          image: nginx:latest
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: healthcheck-config
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 3
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 3
            periodSeconds: 5
