apiVersion: v1
kind: Service
metadata:
  name: healthcheck-service
  namespace: default
spec:
  selector:
    app: healthcheck-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
